// flow-typed signature: 65e538e5a059ee069b5f59232ce6f21a
// flow-typed version: <<STUB>>/jestpack_v^0.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jestpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jestpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jestpack/example/__mocks__/lodash/array/last' {
  declare module.exports: any;
}

declare module 'jestpack/example/__mocks__/path' {
  declare module.exports: any;
}

declare module 'jestpack/example/setup' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/bar/__tests__/bar' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/bar/bar' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/baz/__mocks__/baz' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/baz/__tests__/baz' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/baz/baz' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/foo/__tests__/foo' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/foo/foo' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/foo/localloader' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/qux/__tests__/qux' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/qux/qux' {
  declare module.exports: any;
}

declare module 'jestpack/example/src/qux/split' {
  declare module.exports: any;
}

declare module 'jestpack/example/webpack.config' {
  declare module.exports: any;
}

declare module 'jestpack/ManualMockLoader' {
  declare module.exports: any;
}

declare module 'jestpack/ModuleLoader' {
  declare module.exports: any;
}

declare module 'jestpack/Plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jestpack/example/__mocks__/lodash/array/last.js' {
  declare module.exports: $Exports<'jestpack/example/__mocks__/lodash/array/last'>;
}
declare module 'jestpack/example/__mocks__/path.js' {
  declare module.exports: $Exports<'jestpack/example/__mocks__/path'>;
}
declare module 'jestpack/example/setup.js' {
  declare module.exports: $Exports<'jestpack/example/setup'>;
}
declare module 'jestpack/example/src/bar/__tests__/bar.js' {
  declare module.exports: $Exports<'jestpack/example/src/bar/__tests__/bar'>;
}
declare module 'jestpack/example/src/bar/bar.js' {
  declare module.exports: $Exports<'jestpack/example/src/bar/bar'>;
}
declare module 'jestpack/example/src/baz/__mocks__/baz.js' {
  declare module.exports: $Exports<'jestpack/example/src/baz/__mocks__/baz'>;
}
declare module 'jestpack/example/src/baz/__tests__/baz.js' {
  declare module.exports: $Exports<'jestpack/example/src/baz/__tests__/baz'>;
}
declare module 'jestpack/example/src/baz/baz.js' {
  declare module.exports: $Exports<'jestpack/example/src/baz/baz'>;
}
declare module 'jestpack/example/src/foo/__tests__/foo.js' {
  declare module.exports: $Exports<'jestpack/example/src/foo/__tests__/foo'>;
}
declare module 'jestpack/example/src/foo/foo.js' {
  declare module.exports: $Exports<'jestpack/example/src/foo/foo'>;
}
declare module 'jestpack/example/src/foo/localloader.js' {
  declare module.exports: $Exports<'jestpack/example/src/foo/localloader'>;
}
declare module 'jestpack/example/src/qux/__tests__/qux.js' {
  declare module.exports: $Exports<'jestpack/example/src/qux/__tests__/qux'>;
}
declare module 'jestpack/example/src/qux/qux.js' {
  declare module.exports: $Exports<'jestpack/example/src/qux/qux'>;
}
declare module 'jestpack/example/src/qux/split.js' {
  declare module.exports: $Exports<'jestpack/example/src/qux/split'>;
}
declare module 'jestpack/example/webpack.config.js' {
  declare module.exports: $Exports<'jestpack/example/webpack.config'>;
}
declare module 'jestpack/ManualMockLoader.js' {
  declare module.exports: $Exports<'jestpack/ManualMockLoader'>;
}
declare module 'jestpack/ModuleLoader.js' {
  declare module.exports: $Exports<'jestpack/ModuleLoader'>;
}
declare module 'jestpack/Plugin.js' {
  declare module.exports: $Exports<'jestpack/Plugin'>;
}
