// flow-typed signature: 90549c11913ce8747c9c62523976ddd3
// flow-typed version: <<STUB>>/jQuery_v^1.7.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jQuery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jQuery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jQuery/grunt' {
  declare module.exports: any;
}

declare module 'jQuery/lib/node-jquery' {
  declare module.exports: any;
}

declare module 'jQuery/src/wrapper' {
  declare module.exports: any;
}

declare module 'jQuery/test/core' {
  declare module.exports: any;
}

declare module 'jQuery/test/css' {
  declare module.exports: any;
}

declare module 'jQuery/test/helpers/helper' {
  declare module.exports: any;
}

declare module 'jQuery/tmp/jquery' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jQuery/grunt.js' {
  declare module.exports: $Exports<'jQuery/grunt'>;
}
declare module 'jQuery/lib/node-jquery.js' {
  declare module.exports: $Exports<'jQuery/lib/node-jquery'>;
}
declare module 'jQuery/src/wrapper.js' {
  declare module.exports: $Exports<'jQuery/src/wrapper'>;
}
declare module 'jQuery/test/core.js' {
  declare module.exports: $Exports<'jQuery/test/core'>;
}
declare module 'jQuery/test/css.js' {
  declare module.exports: $Exports<'jQuery/test/css'>;
}
declare module 'jQuery/test/helpers/helper.js' {
  declare module.exports: $Exports<'jQuery/test/helpers/helper'>;
}
declare module 'jQuery/tmp/jquery.js' {
  declare module.exports: $Exports<'jQuery/tmp/jquery'>;
}
