// flow-typed signature: 4427acebf4965d553fed4a7db73048a7
// flow-typed version: <<STUB>>/path_v^0.12.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'path/path' {
  declare module.exports: any;
}

// Filename aliases
declare module 'path/path.js' {
  declare module.exports: $Exports<'path/path'>;
}
