// flow-typed signature: 2b556f87628f5ad6151544267214cb96
// flow-typed version: <<STUB>>/react-forms_v^2.0.0-beta35/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-forms'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-forms' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-forms/lib/react-forms' {
  declare module.exports: any;
}

declare module 'react-forms/s/example/basic-form' {
  declare module.exports: any;
}

declare module 'react-forms/s/index' {
  declare module.exports: any;
}

declare module 'react-forms/webpack.build.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-forms/lib/react-forms.js' {
  declare module.exports: $Exports<'react-forms/lib/react-forms'>;
}
declare module 'react-forms/s/example/basic-form.js' {
  declare module.exports: $Exports<'react-forms/s/example/basic-form'>;
}
declare module 'react-forms/s/index.js' {
  declare module.exports: $Exports<'react-forms/s/index'>;
}
declare module 'react-forms/webpack.build.config.js' {
  declare module.exports: $Exports<'react-forms/webpack.build.config'>;
}
