// flow-typed signature: 010542978d940cf5ac2cad6bc4386f52
// flow-typed version: <<STUB>>/react-infinite-scroller_v^1.0.6/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-infinite-scroller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-infinite-scroller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-infinite-scroller/dist/InfiniteScroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-infinite-scroller/dist/InfiniteScroll.js' {
  declare module.exports: $Exports<'react-infinite-scroller/dist/InfiniteScroll'>;
}
declare module 'react-infinite-scroller/index' {
  declare module.exports: $Exports<'react-infinite-scroller'>;
}
declare module 'react-infinite-scroller/index.js' {
  declare module.exports: $Exports<'react-infinite-scroller'>;
}
