// flow-typed signature: 161ad6cf5093c28e764aea34a0bee729
// flow-typed version: <<STUB>>/reset-css_v^2.2.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reset-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reset-css' {
  declare module.exports: any;
}
